### PR TITLE
change GM/T SM2 Cryptography lib implementation

### PR DESCRIPTION
**Pull request by Shang-QY**

### CODE REVIEW

**Comment by Ddnirvana** [comment]
@fengerhu1 Erhu, please help review this PR.

**Review by fengerhu1 — COMMENTED** [review]
Please fix the attestation bugs (trigger two attestation requests using the same nonce, the attestation report will change)

**Comment by Shang-QY** [comment]
When our monitor hash an enclave, it will hash all the pt entries in page table, which contain untrusted memory and kbuffer. It causes enclave hash varies between each  setup. So we need to set untrusted memory to 0.

**Comment by Shang-QY** [comment]
When sign_tool emulate the hash process at user-mode, it also sets untrusted memory to 0. That can make hash the same in sign_tool and monitor.

**Review by fengerhu1 — APPROVED** [review]
Fine，thanks

**Review by fengerhu1 — APPROVED** [review]

**Review by Penglai-Enclave — APPROVED** [review]
Thanks, all

**Pull request merged**
